spring:
  application:
    name: config-server
  profiles:
    active:
      - vault, native, git
  cloud:
    config:
      import: vault://
      server:
        native:
          search-locations: classpath:/config
        git:
          uri: https://github.com/INotEnemy/cloud-config
          default-label: master
#          clone-on-start: true
          username: #name
          password: #password
          searchpaths: /* #kafkaexample,eurekaserver,demomicroservice,springbootadmin, gatewayserver
        vault:
          port: 8200
          host: 127.0.0.1
          kvVersion: 2
          scheme: http
          uri: http://127.0.0.1:8200
          authentication: TOKEN
          token: #token_value

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/ #{cipher}5b3fa6dd2a47d4999c229cf6bf570a300af8374a5111744b6cee4ad6bc9898e728e8d7439017e12a31753e5325ea385a

management:
  endpoints:
    web:
      exposure:
        include: "*"

encrypt:
  key: #key

server:
  port: 8071